# Generated by Django 5.2.3 on 2025-11-14 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('months', models.PositiveSmallIntegerField(choices=[(1, '1 месяц – 19.95 USDT'), (3, '3 месяца – 58 USDT')])),
                ('usdt_amount', models.DecimalField(decimal_places=2, editable=False, max_digits=8)),
                ('wallet', models.CharField(default='TVzN...', max_length=64)),
                ('tx_hash', models.CharField(blank=True, max_length=128, verbose_name='TxID транзакции')),
                ('status', models.CharField(choices=[('P', 'Ожидает проверки'), ('A', 'Подтверждено')], default='P', max_length=1)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trial_end', models.DateTimeField()),
                ('paid_until', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
