# Generated by Django 5.2.3 on 2025-08-18 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
    migrations.CreateModel(
        name='MainLeague',
        fields=[],  # Оставьте пустым
        options={
            'db_table': 'new_main_league',
            'managed': False,
        },
    ),
]