# Generated by Django 5.2.3 on 2025-11-05 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainLeague',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('home', models.CharField(max_length=100)),
                ('away', models.CharField(max_length=100)),
                ('one_o', models.FloatField()),
                ('one_e', models.FloatField()),
                ('x_o', models.FloatField()),
                ('x_e', models.FloatField()),
                ('two_o', models.FloatField()),
                ('two_e', models.FloatField()),
                ('bts_o', models.FloatField()),
                ('bts_e', models.FloatField()),
                ('bts_no_o', models.FloatField()),
                ('bts_no_e', models.FloatField()),
                ('over_o', models.FloatField()),
                ('over_e', models.FloatField()),
                ('under_o', models.FloatField()),
                ('under_e', models.FloatField()),
                ('first_half', models.CharField(max_length=50, null=True)),
                ('match', models.CharField(max_length=50, null=True)),
                ('goals', models.CharField(max_length=50, null=True)),
                ('league', models.CharField(max_length=50, null=True)),
                ('link', models.URLField(max_length=255, null=True)),
                ('notes', models.TextField(null=True)),
                ('league_id', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'new_main_league',
                'managed': False,
            },
        ),
    ]
