# Generated by Django 5.2.3 on 2025-08-18 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            sql="ALTER TABLE new_main_league ADD COLUMN IF NOT EXISTS league_id INTEGER;",
            reverse_sql="ALTER TABLE new_main_league DROP COLUMN IF EXISTS league_id;"
        ),
    ]
