# Generated by Django 5.2.3 on 2025-11-18 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_managers_alter_customuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Access expires'),
        ),
    ]
