# Generated by Django 5.2.3 on 2025-11-18 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_expires_at'),
    ]

    operations = [
    ]
