# Generated by Django 5.2.3 on 2025-11-20 10:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20251118_1028'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhitelistedDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_hash', models.CharField(max_length=64, unique=True)),
                ('reason', models.CharField(default='admin', help_text='Причина добавления в белый список', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='devicefingerprint',
            name='users',
        ),
        migrations.AddField(
            model_name='devicefingerprint',
            name='last_seen',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='devicefingerprint',
            name='skip_verification',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.devicefingerprint')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['device', 'created_at'], name='users_regis_device__61b339_idx'), models.Index(fields=['email'], name='users_regis_email_ae87b1_idx')],
            },
        ),
    ]
